import java.util.HashMap;
import java.util.Random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


enum Suit { Spade, Diamond, Club, Heart}
enum Rank { ace, two , three, four, five, six, seven, eight, nine, ten, jack, queen, king}

class cards {
	private  Suit suit;
	private  Rank rank;
	private  boolean isdelt;
	
	cards(Suit suit, Rank rank, boolean isdelt){
		this.suit=suit;
		this.rank=rank;
		this.isdelt=isdelt;
	}
	public Suit getSuit(){
		return suit; 
	}
	public Rank getRank(){
		return rank;
	}
	public void setIsDelt(){
		this.isdelt = true;
	}
	public boolean getIsDelt(){
		return this.isdelt;
	}
	public String toString(){
		return ("This card is of suit:"+getSuit()+" & rank :"+getRank());
	}
}

public class App {
	private HashMap<Integer, cards> deck;
	private int calls;
	App(){
		calls = 0;
		deck= new HashMap<Integer, cards>();
		int index =1;
		for (Suit suit: Suit.values()){
			for (Rank rank: Rank.values()){
				deck.put(index++, new cards(suit, rank, false));
			}
		}
	}
	
    public int shuffleCards(){
    	Random rand = new Random();
    	int n = rand.nextInt(52)+1;
    	return n;
    }
    public void dealOneCard(){
    	if (this.calls < 52) {
	    	cards temp = deck.get(shuffleCards());
	    	
	    	if (temp.getIsDelt()) {
	    		dealOneCard();
	    	} else {
	    		this.calls+=1;
	    		temp.setIsDelt();
	    		System.out.println("Card :"+calls+" "+ temp.getSuit() +" of "+temp.getRank());
	    	}
    	} else {
    		System.out.println("All Cards are delt");
    	}
    }
    public static void main(String[] args) {
        
        App app = new App();
        for (int i=1; i<54; i++){
        app.dealOneCard();
        }
        
    }
}